# Generated by Django 3.0.5 on 2020-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('primary_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French')], default='English', max_length=100)),
                ('learning_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French')], default='English', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N/A', max_length=10)),
                ('location', models.CharField(default='Earth', max_length=100)),
                ('profile_picture', models.URLField(default='https://i.imgur.com/OYQulGk.png')),
            ],
        ),
    ]
