# Generated by Django 3.0.5 on 2020-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_language',
            field=models.ManyToManyField(related_name='primary_language', to='mainapp.Language'),
        ),
    ]
