# Generated by Django 3.0.5 on 2020-04-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200417_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('match_time', models.DateTimeField(auto_now=True)),
                ('creat_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_creator', to='mainapp.Profile')),
                ('other_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='mainapp.Profile')),
            ],
        ),
    ]
