# Generated by Django 3.0.5 on 2020-04-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200416_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='alpha_3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
