# Generated by Django 3.0.5 on 2020-04-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='creat_by_profile',
            new_name='profile_1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='other_profile',
            new_name='profile_2',
        ),
    ]
