# Generated by Django 3.0.5 on 2020-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200416_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learning_language',
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_language',
            field=models.ManyToManyField(related_name='learning_language', to='mainapp.Language'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_language',
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_language',
            field=models.ManyToManyField(related_name='primary_language', to='mainapp.Language'),
        ),
    ]
