# Generated by Django 3.0.5 on 2020-04-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
