# Generated by Django 3.0.5 on 2020-04-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_icon',
            field=models.CharField(default='paw', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='nothing here', null=True),
        ),
    ]
