# Generated by Django 3.0.5 on 2020-04-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
    ]
