# Generated by Django 3.0.5 on 2020-05-09 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200422_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Profile')),
                ('profiles_liked', models.ManyToManyField(related_name='profiles_liked', to='mainapp.Profile')),
            ],
        ),
    ]
