# Generated by Django 3.0.5 on 2020-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='nothing here', null=True),
        ),
    ]
