# Generated by Django 3.0.5 on 2020-04-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='profiles_liked',
            field=models.ManyToManyField(related_name='profiles_liked', to='mainapp.Profile'),
        ),
    ]
