# Generated by Django 3.0.4 on 2020-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Earth', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('DE', 'German'), ('FR', 'French')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://i.imgur.com/OYQulGk.png'),
        ),
    ]
