# Generated by Django 3.0.4 on 2020-04-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200401_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French')], default='EN', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French')], default='EN', max_length=100),
        ),
    ]
